# Generated by Django 5.2.2 on 2025-06-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culinarycategory',
            options={'verbose_name_plural': 'Culinary Categories'},
        ),
        migrations.AlterModelOptions(
            name='culinaryspot',
            options={'verbose_name_plural': 'Culinary Spots'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='facilitymaster',
            options={'verbose_name_plural': 'Facility Masters'},
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name_plural': 'Opening Hours'},
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set(),
        ),
    ]
