# Generated by Django 5.2.2 on 2025-06-08 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0002_alter_culinarycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culinarycategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='culinarycategory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
