# Generated by Django 5.2.2 on 2025-06-17 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'Property Type', 'verbose_name_plural': 'Property Types'},
        ),
        migrations.AlterField(
            model_name='annualpopulation',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_populations', to='wildlife.property'),
        ),
        migrations.AlterField(
            model_name='annualpopulation',
            name='taxon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_populations', to='wildlife.taxon'),
        ),
        migrations.AlterField(
            model_name='annualpopulation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_populations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisations', to='wildlife.province'),
        ),
        migrations.AlterField(
            model_name='property',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='properties', to='wildlife.organisation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='properties', to='wildlife.propertytype'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='properties', to='wildlife.province'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_taxa', to='wildlife.taxon'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='taxon_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxa', to='wildlife.taxonrank'),
        ),
    ]
