# Generated by Django 5.2.2 on 2025-06-22 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0002_alter_propertytype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'Property type', 'verbose_name_plural': 'Property types'},
        ),
        migrations.AlterField(
            model_name='annualpopulation',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlife.property'),
        ),
        migrations.AlterField(
            model_name='annualpopulation',
            name='taxon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlife.taxon'),
        ),
        migrations.AlterField(
            model_name='annualpopulation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wildlife.province'),
        ),
        migrations.AlterField(
            model_name='property',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wildlife.organisation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wildlife.propertytype'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wildlife.province'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlife.taxon'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='taxon_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildlife.taxonrank'),
        ),
    ]
