# Generated by Django 5.2.2 on 2025-06-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0003_alter_propertytype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
    ]
