# Generated by Django 5.2.2 on 2025-06-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0004_alter_property_options_alter_property_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonrank',
            name='rank_level',
            field=models.IntegerField(blank=True, help_text='Rank level for sorting purposes', null=True),
        ),
    ]
